version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    user: 1000:1000
    container_name: web
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:10.8
    user: 1000:1000
    container_name: db
    restart: unless-stopped
    ports:
      - 3601:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=web_dev_company
      - MARIADB_ROOT_PASSWORD=root

  composer:
    image: composer:2.3.7
    user: 1000:1000
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - web

  npm:
    image: node:16-alpine
    user: 1000:1000
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: npm